### ISSUE TITLE
QA2 PDF Form - Recasting Questions & Unexpected Error Message

### ISSUE THREAD

**Issue by slmessier** [BC89/sha_oed_issues#217]
- Some of the PDFs are created with repeating questions and when you try to edit the QA2 the system gives and error message.

**Comment by slmessier** [comment]
From: Scott Messier 
Sent: Tuesday, July 07, 2015 11:17 AM
To: Tad Daniel
Cc: Heidi Hammel
Subject: RE: QA2 updates

Hi Tad,
If possible, could you provide some additional information regarding the first issue – “Some of the PDFs are created with repeating questions and when you try to edit the QA2 the system gives and error message”:
•	Sample PDF’s that show the issue
•	Screen cap of the error message that is displayed
•	Project # (s) that correspond to QA2 inspections where the issue is occurring
•	The specific steps to the workflow so that we could recreate the issue

**Comment by slmessier** [comment]
**Please investigate the issue** using the information provided below from Tad's feedback:
1. **Issue can be replicated using _Contract Number BA0725185_** 
2. **PDF issue showing repeated questions can be replicated by clicking on _Print/PDF_ button**
3. **Error message can be replicated by clicking on _View_ or _Edit_ buttons**

![image](https://cloud.githubusercontent.com/assets/4098544/8580613/8b6b497a-2589-11e5-8c98-aba3d2f64754.png)

PDF with Repeated Questions:
![image](https://cloud.githubusercontent.com/assets/4098544/8580633/b17fb09c-2589-11e5-9546-1571a2d9c8ef.png)

**Comment by kanglu666** [comment]
issues found and Fixed, ready for testing
1: Error message was caused by the NPDES_NO, PERMIT_NO fields, that only have length 20 in QA2_Insp table, however PERMIT_NO in PROJ_PERMITS table has length 50. (schema updated)
2: Duplicate data records cleaned. (Not really sure why there are some duplicate data, they might be created by multiple quick click the "save" button, the first click save process not finish yet, then click the second time, UI updated for this. )

**Comment by slmessier** [comment]
validated successfully in KCI DEV - updated to Ready for Production

**Comment by Tad-Daniel** [comment]
item completed
